spring:
  application:
    name: curl-executor

monitor:
  cron-expression: "0 * * * * *"
  target-endpoints:
    - http://localhost:7000/actuator/info
    - https://github.com
    - https://www.google.com
