spring:
  profiles:
    active: local
  application:
    name: endpoint-monitor

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - env
          - health

monitor:
  cron-expression: "0 * * * * *"
  max-timeout: 30000