spring:
  application:
    name: endpoint-monitor

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - env
          - health

monitor:
  cron-expression: "0 * * * * *"