spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/endpointmonitor
    username: endpointmonitor
    password: endpointmonitor
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db.changelog-master.yaml
    url: jdbc:postgresql://localhost:5432/endpointmonitor
    user: endpointmonitor
    password: endpointmonitor

influx:
  url: http://localhost:8086
  token: 7uRrgpomLPMhGclw9ALX1GENt2rAkS3lTwl4XL6VSduDqLbGouIUqKtJae7IKlVUkEDiC9rnI2Hpouaqf4a2UA==
  org: myorg
  bucket: monitoringv2

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace