spring:
  profiles:
    active: local
  application:
    name: endpoint-monitor

info:
  app:
    name: ${spring.application.name}
    description: Endpoint Monitor Service
    version: ${project.version}
  build:
    artifact: @project.artifactId@
    name: @project.name@
  java:
    version: @java.version@

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - env
          - health

monitor:
  cron-expression: "0 * * * * *"
  max-timeout: 30000